<?php foreach ($this->entries as $entry): ?>
	<?php $sciezka = $entry->getPictureName();
    echo "<img  class=\"main\" src=\"$sciezka\">" ?>
<?php endforeach ?>

<div id="main_content">

<p class="main_text">
    <?php foreach ($this->entries as $entry): ?>    
    <?php echo $entry->getContentLng()	 ?>
    <?php endforeach ?>
</p>

<div id="card_button">
	<a href="/files/regulamin.pdf"><p class="card_button"><span>REGULAMIN</span></p></a>
</div>

</div>


