<?php echo $this->doctype() ?> 
<html>
<head>
	<meta charset="utf-8">
	<title>Buffet</title>
	<?php echo $this->headLink()
		->appendStylesheet('/css/redmond/jquery-ui-1.8.19.custom.css')
		->appendStylesheet('/css/global.css') ?>
	<?php echo $this->headScript()
		->prependFile('/js/admin.js')
		->prependFile('/js/jquery-ui-1.8.18.min.js')
		->prependFile('/js/jquery-1.7.2.min.js') ?>
	
	<script type="text/javascript">
		imgs = [];
		var pos  = 0;

		function chImg() {
			var i = document.getElementById( 'imgField' );
			if (!i || !imgs.length) return;
	
			i.src = imgs[ pos++ ];
	
			if( pos >= imgs.length ) {
				pos = 0;
			}

      window.setTimeout( 'chImg()', 3000 );
   }

	</script>
</head>

<body onload=chImg();>
    <div id="priority_messages">
	<ul>
	<?php foreach ($this->priorityMessenger() as $label => $messages) : ?>
		<?php if (count($messages)) : ?> 
			<li class="<?php echo $label ?>_message">
				<ul class="<?php echo $label ?>_message">
				<?php foreach ($messages as $message) : ?>
					<li><?php echo $message ?></li>
				<?php endforeach; ?>
				</ul>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
	</ul>
</div>
    
    
	<div id="container">
		<div id="left">
			<div id="image8"></div>
			<div id="menu_left_admin">
				<ul>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'event', 'action'=>'index', 'lang'=>'pl', 'where'=>'news'), null, true); ?>">Strona NEWS</a>
					</li>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'event', 'action'=>'index', 'lang'=>'pl', 'where'=>'announcement'), null, true); ?>">Strona ZAPOWIEDZI</a>
					</li>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'event', 'action'=>'index', 'lang'=>'pl', 'where'=>'archive'), null, true); ?>">Strona ARCHIWUM</a>
					</li>
                    <li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'gallery', 'action'=>'index', 'lang'=>'pl')); ?>">Strona FOTO</a>
					</li>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'partner', 'action'=>'index', 'lang'=>'pl'), null, true); ?>">Strona PARTNERZY</a>
					</li>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'information', 'action'=>'index', 'lang'=>'pl'), null, true); ?>">Pozostałe PODSTRONY</a>
					</li>
					<li>
						<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'picture', 'action'=>'index', 'lang'=>'pl'), null, true); ?>">Współdzielone zdjęcia</a>
					</li>
				</ul>
			</div>
		</div>
		
		<div id="right">
			<div id="image2356">
				<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'index', 'action'=>'index', 'lang'=>'pl'), null, true); ?>"><div id="image2"></div></a>
				<div id="image356">
					<div id="image56">
						<div id="menu_top">
							<ul class="menu_poziome">
								<li class="menu_poziome">
									<a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'event', 'action'=>'add', 'lang'=>'pl'), null, true); ?>">DODAJ NOWY EVENT</a>
								</li>
							</ul>
						</div>
						
					</div>
				</div>
			</div>
			<div id="main">
				<?php echo $this->layout()->content ?>
			</div>
			
		</div>
		<div style="clear: both;"></div>
	</div>
</body>
</html>

				