<div id="details">


	<?php foreach ($this->entries as $entry): ?>

	<div id="details_picture">
		<?php 
		if ($entry->getPictureName() == null)
    		{
    			echo "<img  class=\"details\" src=\"/images/www_leyout_buffet_buffet_text.gif\">";
    		}
    	else
    	{
    	$sciezka = $this->escape($entry->getPictureName());
    	echo "<img  class=\"details\" src=\"$sciezka\">";
    	} 
    	?>
	</div>
	
	<div id="details_cont">
		<div id="details_title">
			<?php echo $this->escape($entry->getDate()) ?>
			<?php echo nl2br($this->escape($entry->getTitleLng())) ?>
		</div>
    
    	<div id="details_content">
    		<?php echo nl2br($this->escape($entry->getContent())) ?>
    	</div>
    	
    	<div id="details_main_back">
    		<a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'index', 'lang'=>$_SESSION['lang']), null, true); ?>"><div id="details_rectangle_back"></div></a>
    		<div id="details_back">...</div>
    	</div>
    </div>
    <?php endforeach ?>
    
    
</div>