<div id="main_content_news">

<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt class="news">
    
    <?php 
    $sciezka = $this->escape($entry->getPictureName());
//    $sciezka = "D:/wiosna.jpg";
//    $sciezka = "/pictures/wiosna.jpg";
    echo "<img  class=\"news\" src=\"$sciezka\">" ?>
    
    <br />
    <p class="news_title"><?php echo $this->escape($entry->getTitle()) ?></p>
    <p class="news_pre_content"><?php echo nl2br($this->escape($entry->getPreContentPl())) ?></p>
    <p class="news_pre_content"><?php echo $this->escape($entry->getPictureId()) ?></p>
    <p class="news_pre_content"><?php echo $this->escape($entry->getPictureName()) ?></p>
    </dt>
    <?php endforeach ?>
</dl>

</div>