<div id="admin_event">
	<p class="admin_tytul">Edycja podstrony FOTO</p>
	
	<a href="<?php echo $this->url(array('action' => 'add')) ?>" class="button">Dodaj nową galerię</a>
	
	<table id="event">
		<tr id="naglowek">
			<td>Lp.</td>
			<td>Tytuł</td>
			<td>Data od</td>
			<td>Zajawka</td>
			<td>Edytuj</td>
			<td>Usuń</td>
		</tr>

		<?php foreach ($this->entries as $lp => $entry): ?>
			<tr onMouseOver="this.style.background='#FFFFCC'" onMouseOut="this.style.background='none'">
				<td><?php echo $lp + 1 ?></td>
				<td id="tytul">
					<a href="<?php echo $this->url(array('action' => 'show', 'id' => $entry->getId())); ?>">
						<?php echo $this->escape($entry->getFolderName()) ?>
					</a>
				</td>
				<td><?php echo date('d.m.Y', strtotime($this->escape($entry->getFolderDate()))) ?></td>
				<td id="pre_content"><?php echo substr(nl2br($this->escape($entry->getFolderContent())), 0, 80) ?></td>
				<td>
					<a href="<?php echo $this->url(array('action' => 'edit', 'id' => $entry->getId())); ?>">
						<img src="/images/edit.jpg" />
					</a>
				</td>
				<td>
					<a href="<?php echo $this->url(array('action' => 'remove', 'id' => $entry->getId())); ?>">
						<img src="/images/drop.jpg" />
					</a>
				</td>
			</tr>
		<?php endforeach ?>

	</table>

</div>
