<div id="admin_event">
	<p class="admin_tytul">Edycja podstrony NEWS</p>
	<table id="event">
		<tr id="naglowek">
			<td>Lp.</td>
			<td>Tytul</td>
			<td>Data od</td>
			<td>Skrocona tresc</td>
			<td>Edytuj</td>
			<td>Usun</td>
		</tr>
	
		<?php $lp = 1 ?>
		<?php foreach ($this->entries as $entry): ?>
		<tr onMouseOver="this.style.background='#FFFFCC'" onMouseOut="this.style.background='none'">
			<td><?php echo $lp++ ?></td>
			<td id="tytul"><?php echo $this->escape($entry->getFolderName())?></td>
			<td><?php echo date('d.m.Y', strtotime($this->escape($entry->getFolderDate())) )?></td>
			<td id="pre_content"><?php echo substr(nl2br($this->escape($entry->getFolderContent())),0, 80) ?></td>
			<td>
				<a href="<?php echo $this->url(array('action' => 'show', 'id' => $entry->getId()));?>">
					<img src="/images/edit.jpg" />
				</a>
			</td>
			<td><a href="#"><img src="/images/drop.jpg" /></a></td>
		</tr>
		<?php endforeach ?>
	
	</table>

</div>
