<div id="main_content_announcement">

<dl>
    <?php foreach ($this->entries as $entry): ?>
    
    <div id="main_content_announcement_picture">
    <?php 
    $sciezka = $this->escape($entry->getPictureName());
    echo "<img  class=\"announcement\" src=\"$sciezka\">" ?>
    </div>
    
	<dt class="announcement">
    <div id="main_content_announcement_cont">
    <p class="announcement_title">
    	<?php echo date('d.m.Y', strtotime($this->escape($entry->getDateFrom())) )?>
    	<?php echo $this->escape($entry->getTitle()) ?>
    </p>
    
    <p class="announcement_pre_content"><?php echo nl2br($this->escape($entry->getPreContentPl())) ?></p>
    </div>
    
    <div id="main_content_announcement_go">
    	<div id="announcement_content_go">...</div>
    	<a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'details', 'id'=>$entry->getId()), null, true);?>"><div id="main_content_rectangle_go"></div></a>
    </div>
    
    </dt>
    <?php endforeach ?>
</dl>

</div>