<div id="admin_event">
	<p class="admin_tytul">Edycja zdjęcia</p>
	<form id="crop-data" action="<?php echo $this->url(
			array('action' => 'crop-photo', 'controller' => $this->controller, 'module' => 'admin'), null, true)?>">
		<a href="<?php echo $this->url(
				array('action' => 'show', 'controller' => $this->controller, 'module' => 'admin',
					'id' => $this->sourceId), null, true)?>" class="button">Anuluj</a>
		
		<input type="hidden" name="sourceId" value="<?php echo $this->sourceId ?>" />
		<input type="hidden" name="id" value="<?php echo $this->photo->getId() ?>" />
		<input type="hidden" name="type" value="<?php echo $this->type ?>" />
		<input type="hidden" id="x1" name="crop[x1]" />
		<input type="hidden" id="y1" name="crop[y1]" />
		<input type="hidden" id="x2" name="crop[x2]" />
		<input type="hidden" id="y2" name="crop[y2]" />
		<input type="hidden" id="w" name="crop[w]" />
		<input type="hidden" id="h" name="crop[h]" />
		<input type="submit" value="Przytnij Zdjęcie" class="button" />
	</form>
	
	<div id="photo-edit">
		<h4>Zdjęcie oryginalne</h4>
		<img src="<?php echo $this->photo->getName() ?>" id="source" />
	</div>
	<script language="Javascript">
		jQuery(function($) {
			var updateForm = function (c) {
				$('#x1').val(c.x);
				$('#y1').val(c.y);
				$('#x2').val(c.x2);
				$('#y2').val(c.y2);
				$('#w').val(c.w);
				$('#h').val(c.h);
			}
			$('#source').Jcrop({
				onSelect: updateForm,
				aspectRatio: <?php echo $this->ratio ?: 1 ?>,
				setSelect: [0, 0, 100, 100 * <?php echo $this->ratio ?: 1 ?>]
			});
		});
	</script>
</div>
