<?php echo $this->doctype() ?>
<html>
<head>
	<meta charset="utf-8">
	<title>Buffet</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
	
	<script type="text/javascript">
   var imgs = new Array('wiosna1.jpg', 'wiosna2.jpg', 'wiosna3.jpg', 'wiosna4.jpg', 'wiosna6.jpg');
   var pos  = 0;

   function chImg()
   {
      var i = document.getElementById( 'imgField' );

      i.src = 'pictures/' + imgs[ pos++ ];

      if( pos >= 4 )
      {
         pos = 0;
      }

      window.setTimeout( 'chImg()', 5000 );
   }
</script>    
</head>

<body onload=chImg();>

<div id="container">
	<div id="left">
		<div id="image8"></div>
		<div id="menu_left">
			<ul>
				<li><a href="offer">OFERTA</a></li>
				<li><a href="partners">PARTNERZY</a></li>
				<li><a href="newsletter">NEWSLETTER</a></li>
				<li><a href="http://www.facebook.com/BUFFETklub" target="_blank">FACEBOOK</a></li>
				<li><a href="http://vimeo.com/" target="_blank">VIMEO</a></li>
				<li><a href="podcast">PODCAST</a></li>
			</ul>
		</div>
	</div>
	
	<div id="right">
		<div id="image2356">
			<div id="image2">
			</div>
			<div id="image356">
				<div id="image3">
				</div>
				<div id="image56">
					<div id="menu_top">
						<ul class="menu_poziome">
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'index'), null, true); ?>">HOME</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'news'), null, true); ?>">NEWS</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'announcement'), null, true); ?>">ZAPOWIEDZI</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'foto'), null, true); ?>">FOTO</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'video'), null, true); ?>">VIDEO</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'card'), null, true); ?>">KARTA</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'archive'), null, true); ?>">ARCHIWUM</a>
							</li>
							<li class="menu_poziome">
								<a href="<?= $this->url(array('controller'=>'contact'), null, true); ?>">KONTAKT</a>
							</li>
						</ul>
					</div>
					<div id="menu_top_lng">
						<ul class="menu_poziome2">
							<li class="menu_poziome2">
								<a href="<?= $this->url(array('controller'=>'index'), null, true); ?>">PL</a>
							</li>
							<li class="menu_poziome2">
								<a href="<?= $this->url(array('controller'=>'index'), null, true); ?>">EN</a>
							</li>
						</ul>	
					</div>
				</div>
			</div>
		</div>
		<div id="image7">
		</div>
		<div id="main">
			<?php echo $this->layout()->content ?>
		</div>
		
	</div>
	<div style="clear: both;"></div>
</div>

</body>

</html>

				