<div id="admin_event">
	<p class="admin_tytul">Edycja podstrony PARTNERZY</p>
	
	<?php echo $this->form ?> 
	 
	<div class="gallery-photos clearfix">	
		<?php foreach ($this->entries as $entry): ?>
		<div class="gallery-photo">
		<?php $sciezka = $this->escape($entry->getName());
    	echo "<img src=\"$sciezka\" height=\"45\" />" ?>
    	<a href="<?php echo $this->url(
				array('module' => 'admin', 'controller' => 'partner', 'action' => 'remove-photo',
					'id' => $entry->getId()), null, true) ?>" class="button" >
				<img src="/images/drop.jpg" "/>
		</a>
    	</div>
		<?php endforeach; ?>

	</div>
</div>