<div id="admin_event">
	<p class="admin_tytul">Informacje o evencie</p>
	<table class="gallery">
		<tr>
			<td>Data od</td>
			<td><?php echo $this->event->getDateFrom() ?></td>
		</tr>
		<tr>
			<td>Data do</td>
			<td><?php echo $this->event->getDateTo() ?></td>
		</tr>
		<tr><td></td></tr>
		<tr><td></td></tr>
		<tr>
			<td>Tytuł [pl]</td>
			<td><?php echo nl2br($this->event->getTitle()) ?></td>
		</tr>
		<tr>
			<td>Zajawka [pl]</td>
			<td><?php echo nl2br($this->event->getPreContentPl()) ?></td>
		</tr>
		<tr>
			<td>Treść [pl]</td>
			<td><?php echo nl2br($this->event->getContentPl()) ?></td>
		</tr>
		<tr><td></td></tr>
		<tr><td></td></tr>
		<tr>
			<td>Tutuł [en]</td>
			<td><?php echo nl2br($this->event->getTitleEn()) ?></td>
		</tr>
		<tr>
			<td>Zajawka [en]</td>
			<td><?php echo nl2br($this->event->getPreContentEn()) ?></td>
		</tr>
		<tr>
			<td>Treść [en]</td>
			<td><?php echo nl2br($this->event->getContentEn()) ?></td>
		</tr>
		
	</table>
	<a href="<?php echo $this->url(array('action' => 'edit', 'id' => $this->event->getId())); ?>" class="button">
		Edytuj <img src="/images/edit.jpg" />
	</a>
	<a href="<?php echo $this->url(array('action' => 'remove', 'id' => $this->event->getId())); ?>" class="button">
		Usuń <img src="/images/drop.jpg" />
	</a>
</div>