<div id="admin_event">

<?php 
if($_SESSION['event_kind']=='news'){
	echo "<p class='admin_tytul'>Edycja podstrony NEWS</p>";
}
elseif ($_SESSION['event_kind']=='archive'){
	echo "<p class='admin_tytul'>Edycja podstrony ARCHIWUM</p>";
}
elseif ($_SESSION['event_kind']=='announcement'){
	echo "<p class='admin_tytul'>Edycja podstrony ZAPOWIEDZI</p>";
}
?>


<table id="event">
	<tr id="naglowek">
		<td>Lp.</td>
		<td>Tytuł</td>
		<td>Data od</td>
		<td>Skrócona tresc</td>
		<td>Edytuj</td>
		<td>Usuń</td>
	</tr>
	
	<?php foreach ($this->entries as $entry): ?>
    <tr onMouseOver="this.style.background='#FFFFCC'" onMouseOut="this.style.background='none'">
    <td><?php echo $this->escape($entry->getId())?></td>
    <td id="tytul"><?php echo $this->escape($entry->getTitle())?></td>
    <td><?php echo date('d.m.Y', strtotime($this->escape($entry->getDateFrom())) )?></td>
	<td id="pre_content"><?php echo substr(nl2br($this->escape($entry->getPreContentPl())),0, 75) ?> ...</td>
	<td><a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'event', 'action'=>'details', 'id'=>$entry->getId(), 'lang'=>'pl'), null, true);?>"><img src="/images/edit.jpg" /></a></td>
	<td><a href="#"><img src="/images/drop.jpg" /></a></td>
    
    </tr>
    <?php endforeach ?>

</table>

</div>