<?php echo $this->partial('event/_event-info.phtml', array('event' => $this->event)); ?>


<div id="admin_event">

<p class="admin_tytul">Zdjęcie eventu</p>
	<?php echo $this->form ?>

	<div class="gallery-photos clearfix">
		<div class="gallery-photo">
			<h4>Zdjęcie duże</h4>
			<?php if ($this->event->hasLargePicture()) : ?>
				<img src="<?php echo $this->escape($this->event->getLargePictureName()) ?>?s=<?php echo time() ?>" width="250" />
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'edit-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getLargePictureId()), null, true) ?>" class="button">
					<img src="/images/edit.jpg" />
				</a>
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'remove-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getLargePictureId()), null, true) ?>" class="button">
					<img src="/images/drop.jpg" />
				</a>
			<?php else : ?>
				Brak;
			<?php endif; ?>
		</div>
		<div class="gallery-photo">
			<h4>Zdjęcie małe</h4>
			<?php if ($this->event->hasSmallPicture()) : ?>
				<img src="<?php echo $this->escape($this->event->getSmallPictureName()) ?>?s=<?php echo time() ?>" width="250" />
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'edit-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getSmallPictureId(),
						'type' => 'small'), null, true) ?>" class="button">
					<img src="/images/edit.jpg" />
				</a>
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'remove-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getSmallPictureId(),
						'type' => 'small'), null, true) ?>" class="button">
					<img src="/images/drop.jpg" />
				</a>
				
			<?php endif; ?>
		</div>
		<div class="gallery-photo">
			<h4>Zdjęcie dla archiwum</h4>
			<?php if ($this->event->hasArchivePicture()) : ?>
				<img src="<?php echo $this->escape($this->event->getArchivePictureName()) ?>?s=<?php echo time() ?>" width="250" />
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'edit-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getArchivePictureId(),
						'type' => 'archive'), null, true) ?>" class="button">
					<img src="/images/edit.jpg" />
				</a>
				<a href="<?php echo $this->url(
					array('module' => 'admin', 'controller' => 'event', 'action' => 'remove-photo',
						'eventId' => $this->event->getId(), 'id' => $this->event->getArchivePictureId(),
						'type' => 'archive'), null, true) ?>" class="button">
					<img src="/images/drop.jpg" />
				</a>
			<?php endif; ?>
		</div>
	<div>
	
</div>
