<table id="galleries">
	<tr>
		<?php foreach ($this->galleries as $gallery) : ?>
		<td>
			<div class="gallery">
				<div class="photos clearfix">
					<div class="preview">
						<img src="<?php echo $gallery->getMainPhoto()->getName() ?>" />
					</div>
					<div class="thumbnails clearfix">
						<?php foreach ($gallery->getActivePhotos() as $photo) : ?>
							<div class="thumbnail"><img src="<?php echo $photo->getName() ?>" /></div>
						<?php endforeach ?>
					</div>
				</div>
			</div>
		</td>
		<?php endforeach ?>
	</tr>
</table>
