<?php $this->headStyle()->captureStart() ?>
	#rectangle-yellow, #rectangle-red {
		display: none;
	}
<?php $this->headStyle()->captureEnd() ?>

<table id="galleries">
	<tr>
		<?php foreach ($this->galleries as $gallery) : ?>
		<td>
			<div class="gallery">
				<div class="photos clearfix">
					<div class="preview">
						<img src="<?php echo phpThumbURL('src='.$gallery->getMainPhoto()->getCroppedName().'&h=472&w=472&zc=C'); ?>" />
					</div>
					<div class="thumbnails clearfix">
						<?php foreach ($gallery->getActivePhotos() as $photo) : ?>
							<div class="thumbnail">
								<img src="<?php echo phpThumbURL('src='.$photo->getCroppedName().'&h=40&w=40&zc=C'); ?>" data-orig="<?php echo phpThumbURL('src='.$photo->getCroppedName().'&h=472&w=472&zc=C'); ?>"/>
							</div>
						<?php endforeach ?>
					</div>
				</div>
				<div class="description">
					<h4><?php echo $gallery->getFolderDate() ?></h4>
					<p><?php echo $this->escape($gallery->getFolderName()) ?></p>
				</div>
			</div>
		</td>
		<?php endforeach ?>
	</tr>
</table>
