<div id="galleries" class="clearfix">
	<?php foreach ($this->galleries as $gallery) : ?>
		<div class="gallery">
			<div class="preview">
				<img src="<?php echo $this->escape($gallery->getMainPhoto()->getName()) ?>" />
			</div>
			<?php foreach ($gallery->getPhotos() as $photo) : ?>
				<div class="thumbnail"><img src="<?php echo $photo->getName() ?>" /></div>
			<?php endforeach ?>
		</div>
		<?php endforeach ?>
</div>
