<div id="admin_event">
	<p class="admin_tytul">Współdzielone zdjęcia na stronie</p>
	
	<a href="<?php echo $this->url(
			array('module' => 'admin', 'controller' => 'picture', 'action' => 'add-photo',), 
			null, true) ?>" class="button">
		Dodaj nowe zdjęcie
	</a> 
	 
	<div class="gallery-photos clearfix">	
		<?php foreach ($this->entries as $entry): ?>
		<div class="gallery-photo">
		<?php $sciezka = $this->escape($entry->getName());
    	echo "<img src=\"$sciezka\" height=\"150\" />" ?>
    	</div>
		<?php endforeach; ?>
		
		

		
	</div>
</div>